---
title: "Data Science I, Midterm Project"
output: github_document
---
##### Load Packages    
```{r Packages, message=FALSE}

# Load Necessary Packages
  library(ggplot2)
  library(tidyverse)
  library(dplyr)
  library(tidyr)
  library(patchwork)

# Preliminary Loading of All Datasets
  NYC_Rental_Price = read.csv("./NYC Rental.csv")
  NYC_Zipcode      = read.csv("./NYC Zipcode.csv")
  US_Housing_Price = read.csv("./US Housing 2023.csv")

```

##### Data Cleaning    
```{r Data Cleaning}

# Raw-Data -> Pivot Longer -> Filter out Redundant Columns
  NYC_Rental_Price = NYC_Rental_Price %>% 
                     select(RegionName, CountyName, starts_with("X")) %>% 
                     janitor::clean_names() %>% 
                     rename("zipcode"="region_name", "county"="county_name") %>% 
                     mutate(county=gsub(" County","",county)) %>% 
                     mutate(across(where(is.numeric), round, 2)) %>% 
                     pivot_longer(cols=starts_with("x"), names_to="date", values_to="rental_price") %>% 
                     mutate(date=gsub("x","",date)) %>% 
                     mutate(date=gsub("_","/",date)) %>%
                     separate(date, into=c("year", "month", "day"), sep="/") %>%
                     select(-day)
  
  NYC_Zipcode = NYC_Zipcode %>% 
                janitor::clean_names() %>% 
                select(county, zip_code, neighborhood) %>% 
                rename("zipcode"="zip_code") %>% 
                mutate(borough=recode(county, "Kings"="Brooklyn", "New York"="Manhattan", "Richmond"="Staten Island")) %>% 
                relocate(zipcode, county, borough)

  US_Housing_Price = US_Housing_Price %>% 
                     janitor::clean_names() %>% 
                     select(city, region_name, state, starts_with("x")) %>% 
                     rename("zipcode"="region_name") %>% 
                     arrange(zipcode) %>%
                     pivot_longer(cols=starts_with("x"), names_to="date", values_to="housing_price") %>% 
                     mutate(date=gsub("x","",date)) %>% 
                     mutate(date=gsub("_","/",date)) %>% 
                     separate(date, into=c("year", "month", "day"), sep="/")

# Rectify incorrect zipcodes
  NYC_Rental_Price %>% group_by(zipcode) %>% filter(n() > 1) %>% distinct(zipcode)  # zipcodes all unique
  US_Housing_Price %>% group_by(zipcode) %>% filter(n() > 1) %>% distinct(zipcode)  # zipcodes all unique
  NYC_Zipcode %>% group_by(zipcode) %>% filter(n() > 1) %>% distinct(zipcode)       # zipcode 10463 and 11201
  
  NYC_Zipcode %>% filter(zipcode==11201 | zipcode==10463) %>% select(zipcode, county, borough) # correct data should be: 11201--Kings--Brooklyn & 10463--Bronx--Bronx
  NYC_Zipcode = NYC_Zipcode %>% filter(!(zipcode==11201 & county=="New York")) %>% filter(!(zipcode==10463 & county=="New York")) # select all correct zipcodes

# Create Merged Dataset
  Merged = left_join(x=NYC_Zipcode, y=NYC_Rental_Price, by="zipcode") %>%
           rename("county"="county.x") %>% 
           relocate(zipcode, county, borough, neighborhood) %>% 
           select(-county.y)

```

##### Tables           
```{r Tables}

# Table 1 -- average rental price in each borough and year
  Table1 = Merged %>% 
           group_by(borough, year) %>% 
           summarise(mean_rental_price=mean(rental_price, na.rm=TRUE)) %>% 
           pivot_wider(names_from=borough, values_from=mean_rental_price) %>% 
           filter(!is.na(year))

# Table 2 --- comparing average rental prices from 2020 to 2021
  Table2 = Merged %>% 
           filter( (year=="2020"|year=="2021") & month==c("1") ) %>% 
           group_by(year) %>% 
           select(zipcode, year, rental_price) %>% 
           rename("January_of_Year"="year") %>% 
           pivot_wider(names_from=January_of_Year, values_from=rental_price) %>% 
           rename("Jan.2020"="2020", "Jan.2021"="2021") %>% 
           arrange(zipcode) %>% 
           mutate(absolute_change = Jan.2021-Jan.2020, relative_percentage_change = (Jan.2021 - Jan.2020) / Jan.2020 * 100) %>% 
           mutate(across(where(is.numeric),round, 2))

# Table 3 --- for each borough, select neighborhood with largest drop in rental price from 2020 to 2021 
  Table3 =  Merged %>% 
            filter(month == "1" & year %in% c("2020", "2021")) %>%
            pivot_wider(names_from = year, values_from = rental_price, names_prefix = "Jan.") %>%
            mutate(drop = Jan.2020 - Jan.2021) %>% 
            filter(!is.na(drop)) %>% 
            group_by(borough) %>%
            arrange(borough, desc(drop)) %>%
            slice(1) %>%
            select(-month, -zipcode, -county)

# Table 4 --- average house price within each ZIP code over 2023
  Table4 = US_Housing_Price %>% 
           group_by(zipcode, year) %>% 
           summarise(mean_housing_price=mean(housing_price)) %>% 
           mutate(year=as.numeric(year), mean_housing_price=round(mean_housing_price,digits=0)) %>% 
           select(-year)
```

##### Plots            
```{r Plots, fig.width=12, fig.height=12, warning=FALSE}

# Plot1 --- NYC Rental Prices within ZIP codes for all available years facilitating comparisons across borough
  Plot1 = Merged %>% 
          filter(!is.na(year)) %>% 
          select(-month) %>% 
          group_by(year, zipcode, borough) %>% 
          summarise(mean_rental_price = mean(rental_price, rm.na=TRUE)) %>% 
          filter(!is.na(mean_rental_price)) %>% 
          ggplot(aes(x=year, y=mean_rental_price, group=zipcode, color=borough, rm.na=TRUE)) +
          geom_smooth(se=FALSE, size=0.25) + 
          facet_wrap(~borough, nrow=1, ncol=5) +
          theme_light() +
          theme(axis.text.x=element_text(angle=40, hjust=0.5, size=10), plot.title=element_text(hjust=0.5), legend.position="bottom") +
          labs(title = "Zipcode-specific Annual Mean Rental Price Trends by Borough (2015-2024)", x = "Year", y = "Annual Mean Rental Price ($)", color = "Borough") +
          guides(fill=guide_legend(nrow=1))
  Plot1

# Plot2 --- distribution of Zipcode level house prices across states facilitating comparison of the distribution of house prices across states
  Plot2 = US_Housing_Price %>% 
          group_by(zipcode, state) %>% 
          summarise(mean_housing_price=mean(housing_price, rm.na=TRUE)) %>% 
          ggplot(aes(x=state, y=mean_housing_price/ 1e6, fill=state)) + 
          geom_boxplot() + 
          labs(title = "Distribution of Zipcode-level House Prices Across States", x = "State", y = "House Price (Million $)") +
          theme_light() +     
          theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom", legend.key.size = unit(0.5, "cm"), axis.text.x = element_text(angle = 45, hjust = 1)) + 
          guides(fill = guide_legend(ncol = 20))
  Plot2
  
# Plot3 --- Zipcode specific housing prices against Zipcode specific rental prices ( In NYC 2023 )
  Plot3 = inner_join(x  = NYC_Rental_Price %>% filter(year==2023) %>% group_by(zipcode) %>% summarise(annual_mean_rental=mean(rental_price)), 
                     y  = US_Housing_Price %>% filter(city=="New York") %>% group_by(zipcode) %>% summarise(annual_mean_housing=mean(housing_price)), 
                     by = "zipcode") %>% 
          ggplot(aes(x=annual_mean_housing/1e6, y=annual_mean_rental), rm.na=TRUE) + 
          geom_point() +
          geom_smooth() +
          labs(title="Zipcode-specific Housing Prices against Zipcode-specific Rental Prices", x="Annual Mean Housing Price (Million $)", y="Annual Mean Rental Price($)") +
          theme_light() + 
          theme(plot.title=element_text(hjust=0.5))
  Plot3

```


